# Generated by Django 5.2.12 on 2026-07-28 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_spinwallet_spinpurchase'),
        ('myapp', '0003_wallet'),
    ]

    operations = [
    ]
