# Generated by Django 5.2.12 on 2026-08-03 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_spinmachinesettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spinmachinesettings',
            name='prize_cherries',
        ),
        migrations.RemoveField(
            model_name='spinmachinesettings',
            name='prize_diamonds',
        ),
        migrations.RemoveField(
            model_name='spinmachinesettings',
            name='prize_sevens',
        ),
        migrations.RemoveField(
            model_name='spinmachinesettings',
            name='prize_two_of_kind',
        ),
        migrations.AddField(
            model_name='spinmachinesettings',
            name='homepage_jackpot_display',
            field=models.CharField(default='84,52,910', help_text='Jackpot prize amount shown on homepage (e.g. 84,52,910 — no ₹ symbol needed)', max_length=50),
        ),
    ]
