# Generated by Django 5.2.12 on 2026-08-03 22:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_spinmachinesettings_prize_cherries_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinFlipSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('win_multiplier', models.DecimalField(decimal_places=2, default='1.90', help_text='Payout multiplier on a win (e.g. 1.90 = 1.9x the bet back, ~5% house edge)', max_digits=4)),
                ('min_bet', models.DecimalField(decimal_places=2, default='10.00', help_text='Minimum bet amount (INR)', max_digits=10)),
                ('max_bet', models.DecimalField(decimal_places=2, default='5000.00', help_text='Maximum bet amount (INR)', max_digits=10)),
                ('is_active', models.BooleanField(default=True, help_text='Show/hide Coin Flip on the homepage')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Coin Flip Settings',
                'verbose_name_plural': 'Coin Flip Settings',
            },
        ),
        migrations.CreateModel(
            name='CoinFlipBet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('choice', models.CharField(choices=[('heads', 'Heads'), ('tails', 'Tails')], max_length=5)),
                ('result', models.CharField(choices=[('heads', 'Heads'), ('tails', 'Tails')], max_length=5)),
                ('won', models.BooleanField(default=False)),
                ('payout', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coinflip_bets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
