# Generated by Django 5.2.12 on 2026-08-03 22:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_coinflipsettings_coinflipbet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_edge_percent', models.DecimalField(decimal_places=2, default='5.00', help_text='House edge as a percentage (e.g. 5.00 = 5%). Lower = better payouts for players.', max_digits=4)),
                ('min_bet', models.DecimalField(decimal_places=2, default='10.00', help_text='Minimum bet amount (INR)', max_digits=10)),
                ('max_bet', models.DecimalField(decimal_places=2, default='5000.00', help_text='Maximum bet amount (INR)', max_digits=10)),
                ('is_active', models.BooleanField(default=True, help_text='Show/hide Dice Roll on the homepage')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dice Roll Settings',
                'verbose_name_plural': 'Dice Roll Settings',
            },
        ),
        migrations.CreateModel(
            name='DiceBet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('direction', models.CharField(choices=[('under', 'Roll Under'), ('over', 'Roll Over')], max_length=5)),
                ('target', models.PositiveSmallIntegerField(help_text='Target number (2-97) chosen by the player')),
                ('roll', models.PositiveSmallIntegerField(help_text='Actual roll, 0-99')),
                ('won', models.BooleanField(default=False)),
                ('multiplier', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('payout', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dice_bets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
