# Generated by Django 5.2.12 on 2026-08-03 22:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_dicesettings_dicebet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CardHighLowSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_edge_percent', models.DecimalField(decimal_places=2, default='5.00', help_text='House edge as a percentage (e.g. 5.00 = 5%). Lower = better payouts for players.', max_digits=4)),
                ('min_bet', models.DecimalField(decimal_places=2, default='10.00', help_text='Minimum bet amount (INR)', max_digits=10)),
                ('max_bet', models.DecimalField(decimal_places=2, default='5000.00', help_text='Maximum bet amount (INR)', max_digits=10)),
                ('is_active', models.BooleanField(default=True, help_text='Show/hide Card High-Low on the homepage')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Card High-Low Settings',
                'verbose_name_plural': 'Card High-Low Settings',
            },
        ),
        migrations.CreateModel(
            name='CardHighLowRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_rank', models.PositiveSmallIntegerField(help_text='2-14 (Ace = 14)')),
                ('current_suit', models.CharField(choices=[('S', 'Spades'), ('H', 'Hearts'), ('D', 'Diamonds'), ('C', 'Clubs')], max_length=1)),
                ('next_rank', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('next_suit', models.CharField(blank=True, choices=[('S', 'Spades'), ('H', 'Hearts'), ('D', 'Diamonds'), ('C', 'Clubs')], max_length=1)),
                ('choice', models.CharField(blank=True, choices=[('higher', 'Higher'), ('lower', 'Lower')], max_length=6)),
                ('status', models.CharField(choices=[('dealt', 'Dealt'), ('resolved', 'Resolved')], default='dealt', max_length=8)),
                ('won', models.BooleanField(null=True)),
                ('multiplier', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('payout', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cardhilo_rounds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
