# Generated by Django 5.2.12 on 2026-08-03 22:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_cardhighlowsettings_cardhighlowround'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AndarBaharSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('win_multiplier', models.DecimalField(decimal_places=2, default='1.90', help_text='Payout multiplier on a win (e.g. 1.90 = 1.9x the bet back, ~5% house edge)', max_digits=4)),
                ('min_bet', models.DecimalField(decimal_places=2, default='10.00', max_digits=10)),
                ('max_bet', models.DecimalField(decimal_places=2, default='5000.00', max_digits=10)),
                ('is_active', models.BooleanField(default=True, help_text='Show/hide Andar Bahar on the homepage')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Andar Bahar Settings',
                'verbose_name_plural': 'Andar Bahar Settings',
            },
        ),
        migrations.CreateModel(
            name='RouletteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_edge_percent', models.DecimalField(decimal_places=2, default='5.00', help_text='House edge as a percentage (e.g. 5.00 = 5%). Lower = better payouts for players.', max_digits=4)),
                ('min_bet', models.DecimalField(decimal_places=2, default='10.00', max_digits=10)),
                ('max_bet', models.DecimalField(decimal_places=2, default='5000.00', max_digits=10)),
                ('is_active', models.BooleanField(default=True, help_text='Show/hide Roulette on the homepage')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Roulette Settings',
                'verbose_name_plural': 'Roulette Settings',
            },
        ),
        migrations.CreateModel(
            name='SicBoSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_edge_percent', models.DecimalField(decimal_places=2, default='5.00', help_text='House edge as a percentage on top of true Big/Small odds (~48.6% each).', max_digits=4)),
                ('min_bet', models.DecimalField(decimal_places=2, default='10.00', max_digits=10)),
                ('max_bet', models.DecimalField(decimal_places=2, default='5000.00', max_digits=10)),
                ('is_active', models.BooleanField(default=True, help_text='Show/hide Sic Bo on the homepage')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sic Bo Settings',
                'verbose_name_plural': 'Sic Bo Settings',
            },
        ),
        migrations.CreateModel(
            name='AndarBaharBet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('choice', models.CharField(choices=[('andar', 'Andar'), ('bahar', 'Bahar')], max_length=5)),
                ('result', models.CharField(choices=[('andar', 'Andar'), ('bahar', 'Bahar')], max_length=5)),
                ('won', models.BooleanField(default=False)),
                ('payout', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='andarbahar_bets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RouletteBet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bet_type', models.CharField(choices=[('color', 'Color'), ('number', 'Number')], max_length=6)),
                ('bet_value', models.CharField(help_text="'red'/'black' for color bets, '0'-'36' for number bets", max_length=10)),
                ('result_number', models.PositiveSmallIntegerField(help_text='0-36')),
                ('result_color', models.CharField(help_text="'red', 'black', or 'green' (for 0)", max_length=5)),
                ('won', models.BooleanField(default=False)),
                ('multiplier', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('payout', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roulette_bets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SicBoBet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('choice', models.CharField(choices=[('big', 'Big'), ('small', 'Small')], max_length=5)),
                ('die1', models.PositiveSmallIntegerField()),
                ('die2', models.PositiveSmallIntegerField()),
                ('die3', models.PositiveSmallIntegerField()),
                ('total', models.PositiveSmallIntegerField()),
                ('won', models.BooleanField(default=False)),
                ('multiplier', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('payout', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sicbo_bets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
