# Generated by Django 5.2.12 on 2026-08-03 22:44

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_andarbaharsettings_roulettesettings_sicbosettings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='andarbaharsettings',
            name='max_bet',
            field=models.DecimalField(decimal_places=2, default=Decimal('5000.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='andarbaharsettings',
            name='min_bet',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='andarbaharsettings',
            name='win_multiplier',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.90'), help_text='Payout multiplier on a win (e.g. 1.90 = 1.9x the bet back, ~5% house edge)', max_digits=4),
        ),
        migrations.AlterField(
            model_name='cardhighlowsettings',
            name='house_edge_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='House edge as a percentage (e.g. 5.00 = 5%). Lower = better payouts for players.', max_digits=4),
        ),
        migrations.AlterField(
            model_name='cardhighlowsettings',
            name='max_bet',
            field=models.DecimalField(decimal_places=2, default=Decimal('5000.00'), help_text='Maximum bet amount (INR)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='cardhighlowsettings',
            name='min_bet',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Minimum bet amount (INR)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='coinflipsettings',
            name='max_bet',
            field=models.DecimalField(decimal_places=2, default=Decimal('5000.00'), help_text='Maximum bet amount (INR)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='coinflipsettings',
            name='min_bet',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Minimum bet amount (INR)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='coinflipsettings',
            name='win_multiplier',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.90'), help_text='Payout multiplier on a win (e.g. 1.90 = 1.9x the bet back, ~5% house edge)', max_digits=4),
        ),
        migrations.AlterField(
            model_name='dicesettings',
            name='house_edge_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='House edge as a percentage (e.g. 5.00 = 5%). Lower = better payouts for players.', max_digits=4),
        ),
        migrations.AlterField(
            model_name='dicesettings',
            name='max_bet',
            field=models.DecimalField(decimal_places=2, default=Decimal('5000.00'), help_text='Maximum bet amount (INR)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='dicesettings',
            name='min_bet',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Minimum bet amount (INR)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='roulettesettings',
            name='house_edge_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='House edge as a percentage (e.g. 5.00 = 5%). Lower = better payouts for players.', max_digits=4),
        ),
        migrations.AlterField(
            model_name='roulettesettings',
            name='max_bet',
            field=models.DecimalField(decimal_places=2, default=Decimal('5000.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='roulettesettings',
            name='min_bet',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='sicbosettings',
            name='house_edge_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='House edge as a percentage on top of true Big/Small odds (~48.6% each).', max_digits=4),
        ),
        migrations.AlterField(
            model_name='sicbosettings',
            name='max_bet',
            field=models.DecimalField(decimal_places=2, default=Decimal('5000.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='sicbosettings',
            name='min_bet',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='spinmachinesettings',
            name='spin_pack_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Price per spin pack (INR)', max_digits=8),
        ),
    ]
