# Generated by Django 5.2.12 on 2026-08-03 23:25

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_teenpattisettings_teenpattibet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackjackSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('win_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.90'), help_text='Payout multiplier on a standard win (e.g. 1.90 = 1.9x the bet back)', max_digits=4)),
                ('blackjack_multiplier', models.DecimalField(decimal_places=2, default=Decimal('2.35'), help_text='Payout multiplier on a natural blackjack (2-card 21), standard is 3:2', max_digits=4)),
                ('min_bet', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=10)),
                ('max_bet', models.DecimalField(decimal_places=2, default=Decimal('5000.00'), max_digits=10)),
                ('is_active', models.BooleanField(default=True, help_text='Show/hide Blackjack on the homepage')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Blackjack Settings',
                'verbose_name_plural': 'Blackjack Settings',
            },
        ),
        migrations.CreateModel(
            name='BlackjackRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deck', models.JSONField(help_text='Remaining shuffled deck: [[rank, suit], ...]')),
                ('player_cards', models.JSONField()),
                ('dealer_cards', models.JSONField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved')], default='active', max_length=8)),
                ('outcome', models.CharField(blank=True, choices=[('win', 'Win'), ('blackjack_win', 'Blackjack Win'), ('lose', 'Lose'), ('push', 'Push')], max_length=13)),
                ('payout', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blackjack_rounds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
