# Generated by Django 5.2.12 on 2026-08-03 23:33

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_blackjacksettings_blackjackround'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaccaratSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.90'), help_text='Payout multiplier when betting Player and Player wins', max_digits=4)),
                ('banker_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.80'), help_text='Payout multiplier when betting Banker and Banker wins (lower than Player — Banker wins slightly more often, mirrors the real-world commission)', max_digits=4)),
                ('tie_multiplier', models.DecimalField(decimal_places=2, default=Decimal('9.00'), help_text='Payout multiplier when betting Tie and the hand ties (~9-10% chance, standard odds are "8 to 1" i.e. 9x total return)', max_digits=5)),
                ('min_bet', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=10)),
                ('max_bet', models.DecimalField(decimal_places=2, default=Decimal('5000.00'), max_digits=10)),
                ('is_active', models.BooleanField(default=True, help_text='Show/hide Baccarat on the homepage')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Baccarat Settings',
                'verbose_name_plural': 'Baccarat Settings',
            },
        ),
        migrations.CreateModel(
            name='BaccaratBet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bet_side', models.CharField(choices=[('player', 'Player'), ('banker', 'Banker'), ('tie', 'Tie')], max_length=6)),
                ('player_cards', models.JSONField()),
                ('banker_cards', models.JSONField()),
                ('player_total', models.PositiveSmallIntegerField(help_text='0-9')),
                ('banker_total', models.PositiveSmallIntegerField(help_text='0-9')),
                ('winner', models.CharField(choices=[('player', 'Player'), ('banker', 'Banker'), ('tie', 'Tie')], max_length=6)),
                ('outcome', models.CharField(choices=[('win', 'Win'), ('lose', 'Lose'), ('push', 'Push')], max_length=4)),
                ('payout', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baccarat_bets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
