# Generated by Django 5.2.12 on 2026-08-03 23:40

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_baccaratsettings_baccaratbet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PokerSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('win_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.90'), help_text='Payout multiplier on a win (e.g. 1.90 = 1.9x the bet back)', max_digits=4)),
                ('min_bet', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=10)),
                ('max_bet', models.DecimalField(decimal_places=2, default=Decimal('5000.00'), max_digits=10)),
                ('is_active', models.BooleanField(default=True, help_text='Show/hide Poker on the homepage')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Poker Settings',
                'verbose_name_plural': 'Poker Settings',
            },
        ),
        migrations.CreateModel(
            name='PokerBet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('player_cards', models.JSONField(help_text='[[rank, suit], ...] x5')),
                ('dealer_cards', models.JSONField(help_text='[[rank, suit], ...] x5')),
                ('player_hand_type', models.CharField(max_length=20)),
                ('dealer_hand_type', models.CharField(max_length=20)),
                ('outcome', models.CharField(choices=[('win', 'Win'), ('lose', 'Lose'), ('push', 'Push')], max_length=4)),
                ('payout', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poker_bets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
