# Generated by Django 5.2.12 on 2026-08-03 23:56

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_pokersettings_pokerbet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RummySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one_group_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.50'), help_text='Payout when the best split has exactly 1 valid group (~30% of hands)', max_digits=5)),
                ('two_group_multiplier', models.DecimalField(decimal_places=2, default=Decimal('35.00'), help_text='Payout when the best split has exactly 2 valid groups (~1.4% of hands)', max_digits=6)),
                ('perfect_multiplier', models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Payout when all 3 groups are valid — extremely rare (not observed in 20,000 simulated hands)', max_digits=7)),
                ('min_bet', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=10)),
                ('max_bet', models.DecimalField(decimal_places=2, default=Decimal('5000.00'), max_digits=10)),
                ('is_active', models.BooleanField(default=True, help_text='Show/hide Rummy on the homepage')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rummy Settings',
                'verbose_name_plural': 'Rummy Settings',
            },
        ),
        migrations.CreateModel(
            name='RummyBet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cards', models.JSONField(help_text='[[rank, suit], ...] x9')),
                ('valid_group_count', models.PositiveSmallIntegerField(help_text='0-3')),
                ('outcome', models.CharField(choices=[('win', 'Win'), ('lose', 'Lose')], max_length=4)),
                ('multiplier', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('payout', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rummy_bets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
