# Generated by Django 5.2.12 on 2026-08-04 00:39

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_rummysettings_rummybet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrashSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_edge_percent', models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='House edge as a percentage (e.g. 5.00 = 5%). Applies uniformly regardless of cash-out timing.', max_digits=4)),
                ('min_bet', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=10)),
                ('max_bet', models.DecimalField(decimal_places=2, default=Decimal('5000.00'), max_digits=10)),
                ('is_active', models.BooleanField(default=True, help_text='Show/hide Crash on the homepage')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Crash Settings',
                'verbose_name_plural': 'Crash Settings',
            },
        ),
        migrations.CreateModel(
            name='CrashRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('crash_multiplier', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cashout_multiplier', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved')], default='active', max_length=8)),
                ('outcome', models.CharField(blank=True, choices=[('win', 'Win'), ('lose', 'Lose')], max_length=4)),
                ('payout', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crash_rounds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
