# Generated by Django 5.2.12 on 2026-08-04 17:48

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_sitesettings_smtpsettings_platformearning'),
    ]

    operations = [
        migrations.CreateModel(
            name='PWASettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(default='Darkshadow', help_text='Full app name shown on the install prompt/splash screen', max_length=100)),
                ('short_name', models.CharField(default='Darkshadow', help_text='Short name shown under the home-screen icon (keep it brief)', max_length=30)),
                ('icon', models.ImageField(blank=True, help_text='Home-screen icon (square PNG, ideally 512x512). Falls back to a built-in icon if not set.', null=True, upload_to='pwa/')),
                ('theme_color', models.CharField(default='#0A1A3C', help_text='Hex color for the browser/OS chrome around the installed app (e.g. #0A1A3C)', max_length=7)),
                ('is_active', models.BooleanField(default=True, help_text='When ON, visitors are offered the "Install App" PWA prompt site-wide')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'PWA Settings',
                'verbose_name_plural': 'PWA Settings',
            },
        ),
        migrations.CreateModel(
            name='SiteCustomization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='DARKSHADOW', help_text='Site name shown in the header/footer logo and browser tab title', max_length=100)),
                ('logo', models.ImageField(blank=True, help_text='Uploaded logo image — only shown when "Use logo image" is ON below', null=True, upload_to='branding/')),
                ('use_logo_image', models.BooleanField(default=False, help_text='ON: show the uploaded logo image. OFF: show the built-in text logo.')),
                ('favicon', models.ImageField(blank=True, help_text='Browser tab icon. Falls back to the built-in icon if not set.', null=True, upload_to='branding/')),
                ('signup_bonus_amount', models.DecimalField(decimal_places=2, default=Decimal('20.00'), help_text="₹ credited to a new user's wallet automatically on signup", max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Customization',
                'verbose_name_plural': 'Site Customization',
            },
        ),
    ]
